BR-72: Add translations
maugonsal/timingWeb pull request #6
Opened 2022-04-08 04:28 UTC by jeissonmoncada001

## Jira link

[BR-72](https://mundobakia.atlassian.net/browse/BR-72)

## Description

Add translations

## How do I test this PR?

- Clone the repository
- Install the dependencies using the 'yarn' command
- Run the application locally using 'yarn start' command

2022-04-08 19:59 UTC, Julian9411 commented on package.json
> +    "react-router-dom": "^6.3.0",
Why add react-router-dom

2022-04-08 20:01 UTC, Julian9411 requested changes

2022-04-08 20:01 UTC, Julian9411 commented on src/App.tsx
> +  <Suspense fallback={null}>
why this Suspense?

2022-04-08 20:56 UTC, jeissonmoncada001 commented on package.json
> +    "react-router-dom": "^6.3.0",
Done!

2022-04-08 21:00 UTC, jeissonmoncada001 commented on src/App.tsx
> +  <Suspense fallback={null}>
Deleted as not necessary

2022-04-11 14:22 UTC, Julian9411 approved these changes

2022-04-11 14:22 UTC, merged